version: 0.2

phases:
  build:
    commands:
      - yarn install
      - yarn run build-storybook
      - export APP_PATH=$(cat up.json | jq -r '.static.prefix')
      - curl -sf https://up.apex.sh/install | sh
      - git init # fix git information retrieval error
      - up deploy ${APP_ENV} --no-build
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /${APP_PATH}*
